checks/mch/src/gpu_direct_acc.F90
- test will fail if not compiled with OpenACC support
- replace depreciated include "mpif.h" with use mpi
- added a loop reduction to test openacc
=> Update gpu direct mch test : GPU only test, use mpi

config/cscs.py
Since all the nodes have GPUs now and the access options have changed I changed the partition to gpu.
I removed the `PrgEnv-intel` since it's no logner available and added `PrgEnv-nvhpc` and `PrgEnv-nvidia`.
=> Update hohgant configuration

checks/prgenv/mpi.py, config/cscs.py, config/hohgant/squashfs.py
hohgant:
```
UENV_MOUNT_FILE=/scratch/e1000/bcumming/balfrin.squashfs ~/reframe \
-c cscs-reframe-tests.git/checks/prgenv/mpi.py \
-C cscs-reframe-tests.git/config/hohgant/squashfs.py -r \
--system hohgant:gpu-squashfs -S build_locally=0 --max-retries 1 -n .*serial.*
```
=> Add squashfs to mpi_init test

config/balfrin/squashfs.py, config/cscs.py, config/hohgant/squashfs.py, config/manali/cpe.py, config/manali/squashfs.py
We have to merge this before https://github.com/reframe-hpc/reframe/pull/2711 is merged.
=> Update strict option in the configuration

checks/prgenv/opencl_check.py, checks/prgenv/src/opencl/Makefile
Signed-off-by: Theofilos Manitaras <manitaras@cscs.ch>
=> Simplify OpenCL tests and adapt for hohgant

checks/containers/sarus/check_cuda_nbody.py, checks/containers/sarus/check_gpu_ids.py, checks/containers/sarus/check_horovod.py, checks/containers/sarus/check_mpi_with_gpudirect.py, checks/containers/sarus/check_osu_benchmarks.py, checks/containers/sarus/check_pull_command.py, checks/containers/sarus/check_pyfr.py, checks/containers/sarus/check_root_squash_bind_mount.py
Signed-off-by: Theofilos Manitaras <manitaras@cscs.ch>
=> [test] Add sarus checks

checks/containers/buildah/buildah_check.py, checks/containers/sarus/check_cuda_nbody.py, checks/containers/sarus/check_gpu_ids.py, checks/containers/sarus/check_osu_benchmarks.py, checks/containers/sarus/check_pull_command.py, checks/containers/sarus/check_root_squash_bind_mount.py, checks/containers/sarus/compare_order_of_nvidia_devices.py, checks/containers/sarus/compare_output_of_native_and_sarus_nvidia_smi.py
Signed-off-by: Theofilos Manitaras <manitaras@cscs.ch>
=> [test] Adapt the container tests for hohgant

checks/prgenv/cuda/cuda_aware_mpi.py
Fix for https://jira.cscs.ch/browse/VCMSA-190
=> Add cuda_aware_mpi * cdt

config/systems/rigi.py
I provide a configuration file for Rigi, as described in [SPCI-125](https://jira.cscs.ch/browse/SPCI-125).
=> Add configuration for Rigi

checks/system/io/ior_check.py
I add a fix for the Ior checks on Pilatus, that takes into account the recent change on the user environment.
=> Add cray module to compile Ior check on Pilatus

Jenkinsfile, checks/prgenv/cuda/nvml_check.py, checks/prgenv/mpi.py, checks/prgenv/src/mpi_thread/Makefile, ci/cpe.yml, config/cscs.py, config/systems/hohgant.py
epic https://jira.cscs.ch/browse/VCMSA-263
+ https://jira.cscs.ch/browse/VCMSA-339
=> [cpe/alps] mpi.py

config/systems/hohgant.py
why ? [because](https://cscs-lugano.slack.com/archives/C037KRHM3RA/p1686570566507689) and https://jira.cscs.ch/browse/VCMSA-354
=> [cpe/alps] update amdgpu config

config/systems/hohgant.py
Same as #91 , but let's also merge in main so that daily pipelines don't fail.
=> Remove aocc environment from hohgant

uenv_checks/prgenv/mpi.py, uenv_checks/prgenv/src/mpi_thread
- https://jira.cscs.ch/browse/VCUE-44
- Tested with:
```bash
UENV_FILE=/scratch/e1000/manitart/myimages/gnu_a100.squashfs \
RFM_CONFIG=~/cscs-reframe-tests.git/config/cscs-uenv.py \
~/R --system hohgant:nvgpu -r -c prgenv/mpi.py
```
=> add prgenv/mpi.py to uenv

checks/libraries/io/netcdf.py, checks/microbenchmarks/cpu/stream/stream.py, checks/mixins/extra_launcher_options.py, checks/prgenv/mpi.py, checks/prgenv/openacc_checks.py, checks/system/slurm/slurm.py, config/manali/cpe.py, config/systems/hohgant.py, uenv_checks/prgenv/mpi.py
https://jira.cscs.ch/browse/VCUE-35
=> Update stream test for cpe

uenv_checks/libraries/io/hdf5.py, uenv_checks/libraries/io/src/h5_subset.f90, uenv_checks/libraries/io/src/h5tutr_subset.cpp
https://jira.cscs.ch/browse/VCUE-45
Tested with /scratch/aistor/piccinal/hdf5/hdf5_jg.squashfs
=> Add hdf5 test for uenv

uenv_checks/prgenv/cuda_samples.py
https://jira.cscs.ch/browse/VCUE-40
=> Revisit cuda samples test for uenv

portable_tests.md, uenv_checks/mixins, uenv_checks/prgenv/cuda_aware_mpi.py
Tested with `/scratch/e1000/manitart/myimages/nvhpc_a100.squashfs`
=> Add Cuda aware mpi test for uenv

portable_tests.md, uenv_checks/prgenv/openacc.py, uenv_checks/prgenv/src/openacc
Tested with `/scratch/e1000/manitart/myimages/nvhpc_a100.squashfs`
=> Add OpenACC tests for uenv

checks/prgenv/cuda/cuda_nvml.py, uenv_checks/prgenv/cuda_nvml.py
https://jira.cscs.ch/browse/VCUE-50
Tested with:
```
UENV_FILE=/scratch/e1000/manitart/myimages/nvhpc_a100.squashfs \
RFM_CONFIG=~/cscs-reframe-tests.git/config/cscs-uenv.py \
~/R --system hohgant:nvgpu -r -c uenv_checks/prgenv/cuda_nvml.py
```
=> Add Cuda nvml check for uenv

config/systems/pilatus.py, config/systems/rigi.py
I provide a fix with the updated resources folder on Pilatus an RIgi.
=> Fix resources folder on Pilatus and Rigi

checks/containers/container_engine/check_cuda_nbody.py, checks/mixins/container_engine.py, ci/cpe.yml, config/systems/clariden.py, portable_tests.md
https://jira.cscs.ch/browse/VCUE-217
=> Add first implementation of CE mixin

checks/mixins/container_engine.py, portable_tests.md
* Add documentation for extra fields.
* Write key/value pairs before TOML tables in the environment config.
=> Create the CE environment before running

checks/prgenv/cuda_nvml.py
https://jira.cscs.ch/browse/VCUE-224
=> [bugfix] Update sanity regex on CUDA NVML test

checks/microbenchmarks/cpu/stream/stream.py
https://jira.cscs.ch/browse/VCUE-225
=> [test] Support Stream microbenchmark on multi-socket systems

checks/tools/profiling_and_debugging/notool.py
=> fix for tools/profiling_and_debugging/notool.py check

checks/microbenchmarks/mpi/osu/osu_run.py, config/cscs.py, config/systems-uenv/todi-uenv.py
https://jira.cscs.ch/browse/VCUE-330
=> Use one socket for osu benchmarks

checks/prgenv/affinity_check.py
https://jira.cscs.ch/browse/VCUE-331
=> Fix affinity check for aarch64

ci/alps_uenv.yml, ci/scripts/alps_uenv.sh
Fix for image(s) without a reframe.yaml file.
Tested with:
```
prgenv-gnu/24.2:v2
netcdf-tools/2024:v1 <-- SKIP
namd/3.0b6:v1           <-- SKIP
icon-wcp/v1:v3
icon-wcp/v1:v2
icon-wcp/v1:v1
icon-wcp/v1:latest
```
=> fix for ci

checks/tools/profiling_and_debugging/linaro-forge.py, ci/scripts/alps_uenv.sh
https://jira.cscs.ch/browse/VCUE-284
Tested with linaro-forge/24.0:1310006277
=> add linaro-forge uenv check

config/systems-uenv/clariden-uenv.py, config/systems-uenv/pilatus-uenv.py, config/systems-uenv/santis-uenv.py, config/systems-uenv/todi-uenv.py
https://jira.cscs.ch/browse/VCUE-343
=> Allow list of commands for uenv activation

checks/microbenchmarks/gpu/hooks.py, config/systems/arolla.py
This PR addressees ReFrame on the system Arolla:
1. Add general configuration for the system
2. Fix typo in hooks.py of microbenchmarks
=> Add Arolla configuration/fix hook.py

checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
Align the reference value on Eiger to the one already set on Pilatus
=> Update reference on Eiger for alloc_speed.py

checks/apps/pytorch/mlperf_storage_ce.py, checks/apps/pytorch/src/unet3d.yaml
increase number of test files and tasks
=> MLperf Storage

checks/system/integration/daint.py, checks/system/integration/eiger.py, checks/system/integration/todi.py, checks/system/integration/utils.py
Add the option to request multiple features for the tests
=> Add multiple features to sysint tests

config/common.py
To try locally you can set `RFM_HTTPJSON_URL=http://log.cscs.ch:31311/reframe` before running.
=> Send data to elastic

checks/apps/quantumespresso/quantumespresso_check.py, checks/apps/quantumespresso/src/README.md, checks/apps/quantumespresso/src/mps-wrapper.sh
=> QuantumEspresso

checks/system/io/ior_check.py
=> Fix IOR exec opts assignment

checks/libraries/dlaf/dlaf.py
DLA-Future added to mc uenv in https://github.com/eth-cscs/alps-uenv/pull/188.
=> Update timings for DLA-Future test and add eiger test

.github/workflows/main.yml, checks/containers/container_engine/cuda_mps.py, checks/containers/container_engine/omb.py, checks/containers/container_engine/ssh.py
Additional tests to increase feature coverage for the Container engine on Alps:
- OSU benchmarks testing
- Traditional MPI communication instead of NCCL communication
- Inter-node and intra-node communication with point-to-point and collective benchmarks
- MPICH and OpenMPI implementations, exercising respectively PMI2 and PMIx support
- SSH hook: checks that using the related annotation the SSH server process is running inside the container
- CUDA MPS hook: checks that using the related annotation the CUDA MPS control daemon is running inside the container
=> Add further checks for the Container Engine

ci/scripts/slack_notify.py
Some pipelines fail because of a timeout and there is no json report. In this case it's useful to send a slack notification for the failure.
=> Send slack notification in case of pipeline failure without report

checks/prgenv/mpi_cpi.py, config/common.py, config/systems/beverin.py, config/systems/bristen.py, config/systems/clariden.py, config/systems/daint.py, config/systems/eiger.py, config/systems/pilatus.py, config/systems/todi.py
Also doing some refactoring and moving the cpe/uenv prod modes in `common.py`
=> Add the new appscheckout modes

checks/system/slurm/slurm.py, config/common.py, config/systems/clariden.py, config/systems/daint.py, config/systems/santis.py, portable_tests.md
https://jira.cscs.ch/browse/VCUE-801
=> Add test for Transparent Hugepages slurm feature

checks/apps/sphexa/sphexa_uenv.py
=> Update sphexa tags
