- checks/apps/cp2k/cp2k_check.py
The reference is updated based on the [95th percentile of the past two months](https://kibana.cscs.ch/s/scs/goto/327958e0-eb05-11ec-b6c7-af1d303f95a4).
> [test] Update reference for small check on dom:mc

- config/cscs.py
When experimenting with pilatus, my tests where being submitted with 1:00:00 wall time... The default queue time on the system is not 10 minutes
> Set the time_limit to Pilatus and eiger mc

- checks/system/slurm/slurm.py
These tests expect
* all partitions listed to be present in a given system (even if
they are not accessible)
* at least one node per partition to be in allocated, reserved, and/or
idle state
* no more than 10% of compute nodes assigned to a partition to be in
a state other than allocated, reserved, and/or idle
> Add slurm queue test availability

- config/cscs.py
Need to remove `compact_test_names` after https://github.com/reframe-hpc/reframe/pull/2574
Now `compact_test_names=True` is the default and only option.
> Remove `compact_test_names` from config

- checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
I propose to remove the lower threshold of the check, as commented in [VCMSA-62](https://jira.cscs.ch/browse/VCMSA-62).
> Remove lower threshold of AllocSpeedTest

- checks/libraries/io/hdf5_compile_run.py
I propose to add an `export` statement to update `LD_LIBRARY_PATH` with `CRAY_LD_LIBRARY_PATH` after loading `cray-hdf5` and `PrgEnv-aocc` on Alps (see the corresponding [HPE support case 5365481562](https://support.hpe.com/connect/s/case/5003f00000MOXUbAAP/cray-sh-liquid-cooled-base-system-code-hdf5-library-version-mismatched-error-with-prgenvaocc)).
> Update LD_LIBRARY_PATH of cray-hdf5

- config/cscs.py
We should merge this only after https://github.com/reframe-hpc/reframe/pull/2620 is merged.
It should fix https://jira.cscs.ch/browse/SD-56508
> Add perflog_ignore in httpjson

- config/cscs.py
I would like to add the configuration of the vcluster Clariden, which is copied from Hohgant, adding the partition `amdgpu` and renaming `gpu` as `nvgpu` (Hohgant is still configured to access only Nvidia nodes with `'access': ['-pnvgpu']`).
> Configuration for vcluster Clariden

- config/cscs.py
Hi, I noticed that time limit is not set in all of our partitions. A (failed) test was keeping the nodes busy for a long time in hohgant.
@kraushm I wasn't sure about arolla/tsa. Do you run longer tests there and prefer to remove it?
> Add time limit to all partitions

- checks/libraries/gridtools/gridtools_tests.py
The test is skipped for a while now in jenkins because of unresolved dependencies:
```
[33mWARNING: could not resolve dependency: ('GridToolsGPURunCheck_1', 'daint:gpu', 'builtin') -> 'GridToolsBuildCheck_gpu'[0m
[33mWARNING: could not resolve dependency: ('GridToolsGPURunCheck_0', 'daint:gpu', 'builtin') -> 'GridToolsBuildCheck_gpu'[0m
[33mWARNING: could not resolve dependency: ('GridToolsCPURunCheck_1', 'daint:gpu', 'builtin') -> 'GridToolsBuildCheck_cpu'[0m
...
```
Instead of fixing the dependency, I thought fixtures may be more suitable for the test.
> Use fixtures in gritools test

- checks/apps/amber/amber_check.py
This includes the Amber checks with 8 nodes to the Eiger cluster.
> Enable 8 node runs on eiger

- checks/microbenchmarks/mpi/osu/osu_tests.py
OSU pt2pt default value of 1000 iterations takes quite long to run; 100 iterations should be sufficient.
This modification requests lowering the number for all systems, but if preferred, a system specific limit would also be ok, I guess.
> Reduce number of iterations

- config/systems/pilatus.py
Hi, we need to update the configuration of Pilatus as described in [SD-58016](https://jira.cscs.ch/browse/SD-58016): the module `cray` will be loaded before loading the Cray Programming Environments.
> Update configuration of Pilatus

- checks/prgenv/environ_check.py
I provide an updated check for Pilatus after the recent change of configuration of ReFrame to match the new environment on the system: the change should fix the tests `CrayVariablesCheckEiger` that are [currently failing in the daily run](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-pilatus-production-daily/detail/reframe-pilatus-production-daily/652/pipeline/).
> Update environment checks for Pilatus

- checks/containers/buildah/buildah_check.py
- config/systems/pilatus.py
The check `ContainerMpichOSUTest` fails on Pilatus in the [daily run of the regression test suite](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-pilatus-production-daily/detail/reframe-pilatus-production-daily/656/pipeline):
```
Lmod Warning: Failed to find the following module(s):
"singularity/3.5.3-eiger" in your MODULEPATH
Try:
$ module spider singularity/3.5.3-eiger
to see if the module(s) are available across all compilers and MPI implementations.
```
The reason is that the module `cray` is not loaded, since the module `singularity` is not created in a toolchain with a `PrgEnv` modulefile: therefore I am adding the request to load the module `cray` in the initialization of the check.
> Add cray module to load singularity

- checks/prgenv/environ_check.py
- checks/system/io/ior_check.py
I provide a fix for the regression tests that need to load the module `cray` on Eiger after the last maintenance.
> Fix cray module for IOR and PrgEnv checks

- config/cscs.py
- config/systems-uenv/hohgant-uenv.py
This PR makes the following changes:
1. The `UENV` variable is used to pass user environments to ReFrame, which uses the following convention, ` --uenv=<file>[:mount-point][,<file:mount-point>]*`
2. Only the first image/mount pair of `UENV` is used
3. The mount point of the uenv and the activation script have to coincide
> Use the new slurm plugin convention for uenvs

- checks/system/io/ior_check.py
The current `/scratch/e1000` hosted on `alpstor` will be read-only as of Oct 25th, therefore the check would fail to write there. I have provided the new path to the `capstor` scratch: it would be better to use the environment variable `$SCRATCH`, if possible.
> [test] Fix IOR on Alps with capstor

- checks/system/io/ior_check.py
The change recently merged in #130 raised a syntax error, therefore  I am reverting back to the absolute path:
```
ERROR: run session stopped: syntax error: invalid syntax (ior_check.py, line 35)
File "/users/lucamar/GitHub/lucamar/cscs-reframe-tests/checks/system/io/ior_check.py", line 35
''${SCRATCH:-/capstor/scratch/cscs}': {
^
SyntaxError: invalid syntax
```
> [test] Fix IOR check

- config/systems/eiger.py
The current path under `/apps/common` won't be accessible any longer on Eiger.
> Update path of resources folder on Eiger

- checks/microbenchmarks/cpu/alloc_speed/alloc_speed.py
The test [fails the performance check](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-pilatus-production-daily/detail/reframe-pilatus-production-daily/936/pipeline/) with the Cray Operating System 2.4 on Pilatus: therefore I provide an updated and slightly degraded performance reference to meet the new reference value.
> Fix performance reference with COS 2.4 on Pilatus

- checks/apps/namd/namd_check.py
I provide a fix for the `NAMD` regression check on Pilatus with Slurm 23.02.7 setting `SRUN_CPUS_PER_TASK`: see [SPCI-235](https://jira.cscs.ch/browse/SPCI-235).
> Fix NAMD CPU threads with Slurm 23.02.7

- checks/apps/paraview/src/coloredSphere.py
Proxy (filters, ProcessIdScalars)  has been deprecated in ParaView 5.12 and will be removed by ParaView 5.14.
> Update ParaView test coloredSphere.py

- checks/prgenv/environ_check.py
CPE 23.12 replaced the environment variable `CRAY_LIBSCI_PREFIX_DIR` with `CRAY_PE_LIBSCI_PREFIX` and `CRAY_PE_LIBSCI_PREFIX_DIR` in the modulefile `cray-libsci`. 
Additionally, the name of the `gcc` module loaded by `PrgEnv-gnu` is now `gcc-native` (see [SPCI-236](https://jira.cscs.ch/browse/SPCI-236) for more details).
Therefore, the sanity patterns `{envvar_prefix}_PREFIX` and `{envvar_prefix}_VERSION` using `envvar_prefix = self.cray_module.upper().replace('-', '_')` do not work any longer for `CrayVariablesCheckEiger`, since the envvar prefix should be `CRAY_PE_LIBSCI` for `cray-libsci` and `GCC` only for `gcc-native`.
I am providing a quick workaround that simply skips the check of `cray-libsci` and `gcc` for the time being.
> Workaround for CrayVariablesCheckEiger with CPE 23.12

- config/cscs.py
- config/systems-firecrest/README.md
As Andreas noticed, the way we are testing now the vars to decide which configs to import can be a bit confusing. They are always true when set. `RFM_FIRECREST=0` is equivalent to `RFM_FIRECREST=1`.
> Improve the firecrest sched docs

- checks/system/slurm/slurm.py
The test `MemoryOverconsumptionMpiCheck` often [fails to meet the expected performance](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-pilatus-production-daily/detail/reframe-pilatus-production-daily/993/pipeline) with `PrgEnv-cray` and `PrgEnv-gnu` on Pilatus with CPE 23.12 and COS 3.0. 
I suggest to increase the tolerance to 10% below the reference value, which will make the test pass on Pilatus as well.
> Update tolerance of MemoryOverconsumptionMpiCheck

- checks/system/integration/todi.py
Check for jq, since it is used in CI-Ext scripts
> Todi: Check for jq

- checks/apps/vasp/src/makefile.include.gh200
- checks/apps/vasp/vasp_check.py
Compilation and testing of VASP on GH200 using uenv.
The matching config file for the uenv is added in https://github.com/eth-cscs/alps-uenv/pull/175.
Similar to #245, `CSCS_REGISTRY_USERNAME` and `CSCS_REGISTRY_PASSWORD` need to be set to pull the uenv image.
> VASP: Add uenv tests for GH200

- config/systems/todi.py
Provide folder with resources on Todi, that would be required for some applications (e.g. `NAMD`)
> Update resourcesdir todi.py

- checks/apps/gromacs/gromacs_check.py
Fix SyntaxError in `checks/apps/gromacs/gromacs_check.py`
> Fix SyntaxError

- config/systems/daint.py
The important change is the comma missing in the `PrgEnv-gnu` environment. But I also fixed a bit the formatting because my editor was complaining.
> Add missing comma in daint configuration

- checks/apps/cp2k/cp2k_uenv.py
- checks/apps/cp2k/src/pika-bind.sh
Adds a minimal `pika-bind.sh` wrapper to ensure that pika gets the correct process mask. A custom version is added so that the existence of the wrapper won't depend on whether the uenv is built with or without DLA-Future support.
The other environment variables come from the DLA-Future reframe test (including #287).
> Set environment variables for pika and DLA-Future in CP2K uenv tests

- ci/alps_cpe.yml
- ci/alps_uenv.yml
Currently the slurm timelimit and the gitlab runner timeout are set to the default one hour.
Sometimes the queueing time can be longer than one hour, even if the slurm job itself could finish in less than an hour. For example, in https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/6557018579987861/835515875116214/-/jobs/9549784370 the job was submitted and queued, but the gitlab job timed out after one hour with the job still in the queue.
This PR explicitly sets a longer, 8 hour, timeout for the gitlab jobs as a whole, which includes slurm queueing time. It then also sets an explicit `SLURM_TIMELIMIT` of one hour (which is what the inferred timelimit is already now on main) for the slurm job itself. For the `setup and pull` job, which as far as I can tell only pulls uenv metadata, …
> Use longer gitlab runner timelimit in firecrest CI configurations

- checks/system/integration/eiger.py
Thanks for submitting #301 @ekouts. May I suggest to replace the check of `/users.OLD` with `/users/cscs`? 
As a matter of fact, `/users.OLD` will be removed from the mount points on the system on June 02 2025.
> Please do not check /users.OLD on Eiger

- config/systems/bristen.py
I wanted to run some checks on Bristen and I realized this repo does not feature a system config for it, so I put together one by copying the Clariden config (the production system for which Bristen is the development counterpart) and mixing in some bits from Balfrin (as an actively used A100 system with an existing config).
I can successfully carry out a dry-run of the CE checks:
```
[bristen][amadonna@nid001060 container_engine]$ /capstor/scratch/cscs/amadonna/reframe-x86/reframe/bin/reframe -C /capstor/scratch/cscs/amadonna/reframe-tests/config/cscs.py -c /capstor/scratch/cscs/amadonna/reframe-tests/checks/containers/container_engine --mode=production -J account=a-csstaff --system bristen --dry-run
WARNING: redefinition of environment '*:builtin': already defined in '<builtin>' …
```
> Added system configuration for Bristen

- checks/apps/cp2k/cp2k_uenv.py
Required by DLA-Future eigensolver to avoid hangs, but since only the cholesky decomposition is used from DLA-Future at the moment in the test, and `FI_MR_CACHE_MONITOR=disabled` slows down the overall run, remove it for now.
We're planning to add a new CP2K test which explicitly uses DLA-Future. We'll add back the environment variable specifically for that test once it's needed.
> Remove `FI_MR_CACHE_MONITOR=disabled` from cp2k uenv test

- config/common.py
These variables will be set during the gitlab runners so we can have a direct link to the pipeline that produced the results in kibana.
> Add ci info in the elastic data

- checks/apps/namd/namd_check_uenv.py
Adjust reference for NAMD for the new Eiger.
For Daint, NAMD seems very stable at 91 so 93 was probably one of the best cases. The tolerance is adjusted to be more in line with the mean and avoid spurious failures.
> [NAMD] Adjust references

- checks/apps/lammps/lammps.py
```console
$ UENV=lammps/2024:v1 reframe -r ...
```
> Return perf_value as float

- checks/prgenv/affinity_check.py
- checks/prgenv/helloworld.py
- checks/prgenv/mpi.py
- checks/system/uenv/uenv_status.py
- ci/alps_uenv.yml
- ci/scripts/alps.sh
- ci/scripts/prepare_uenvs.sh
- config/common.py
- config/cscs.py
- config/utilities/uenv.py
Merge the UENV and CPE pipelines.
Additional changes in the PR:
- In order to avoid running simple generic tests in almost *every* applications uenv (because some tests just need an `+mpi` feature), we introduce a new feature `prgenv` to differentiate between uenvs that we want to test for simple compilations.
- We use [this branch](https://github.com/ekouts/reframe/tree/feat/sanity_logging) of reframe, until https://github.com/reframe-hpc/reframe/pull/3516 is merged.
> Merge pipelines

- ci/scripts/alps.sh
All pipelines are currently failing to install reframe, e.g. https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/6557018579987861/835515875116210/-/jobs/11124442179#L37.
```
unzip:  cannot find or open develop.zip, develop.zip.zip or develop.zip.ZIP.
```
> Fix handling of arguments in `launch_reframe_1arg` CI helper

- checks/apps/vasp/src/makefile.include.gh200
- checks/apps/vasp/vasp_check_uenv.py
The VASP uenv build test fails for v6.5.1 on daint.
The makefile for VASP needs to be updated to find a NVHPC provided Fortran module.
> Fix uenv build test with vasp v6.5.1
